const { pool } = require('../src/config/db');

async function runCleanupAndMigration() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    console.log('1. Updating constraints for BLOQUEADO status...');
    await client.query(`
      ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_estado_check;
      ALTER TABLE usuarios ADD CONSTRAINT usuarios_estado_check CHECK (estado IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO'));
      
      ALTER TABLE asociados DROP CONSTRAINT IF EXISTS asociados_estado_asociado_check;
      ALTER TABLE asociados ADD CONSTRAINT asociados_estado_asociado_check CHECK (estado_asociado IN ('ACTIVO', 'INACTIVO', 'SUSPENDIDO', 'BLOQUEADO'));
    `);

    console.log('2. Cleaning up test records generated by automated test...');
    // Delete transactions for test account (if any associated with test persona/cuenta)
    await client.query(`
      DELETE FROM transacciones WHERE id_cuenta IN (
        SELECT c.id_cuenta FROM cuentas c 
        JOIN asociados a ON c.id_asociado = a.id_asociado 
        JOIN personas p ON a.id_persona = p.id_persona 
        WHERE p.cui_dpi IN ('4000000000005', '4000000000006')
      );
    `);

    // Delete accounts for test associates
    await client.query(`
      DELETE FROM cuentas WHERE id_asociado IN (
        SELECT a.id_asociado FROM asociados a 
        JOIN personas p ON a.id_persona = p.id_persona 
        WHERE p.cui_dpi IN ('4000000000005', '4000000000006')
      );
    `);

    // Delete bank accounts
    await client.query(`
      DELETE FROM movimientos_cuenta_bancaria WHERE id_cuenta_bancaria IN (
        SELECT cb.id_cuenta_bancaria FROM cuenta_bancaria cb 
        JOIN personas p ON cb.id_persona = p.id_persona 
        WHERE p.cui_dpi IN ('4000000000005', '4000000000006')
      );
      DELETE FROM cuenta_bancaria WHERE id_persona IN (
        SELECT id_persona FROM personas WHERE cui_dpi IN ('4000000000005', '4000000000006')
      );
    `);

    // Delete associates
    await client.query(`
      DELETE FROM asociados WHERE id_persona IN (
        SELECT id_persona FROM personas WHERE cui_dpi IN ('4000000000005', '4000000000006')
      );
    `);

    // Delete users
    await client.query(`
      DELETE FROM historial_estados_usuario WHERE id_usuario_modificado IN (
        SELECT id_persona FROM personas WHERE cui_dpi IN ('4000000000005', '4000000000006')
      );
      DELETE FROM usuarios WHERE id_persona IN (
        SELECT id_persona FROM personas WHERE cui_dpi IN ('4000000000005', '4000000000006')
      );
    `);

    // Delete personas (only the test ones for DPI 4000000000005 / 4000000000006)
    await client.query(`
      DELETE FROM personas WHERE cui_dpi IN ('4000000000005', '4000000000006');
    `);

    console.log('3. Cleaning up dummy case CASO-AFIL-2026-1002...');
    await client.query(`
      DELETE FROM solicitudes_afiliacion_agencia WHERE numero_caso = 'CASO-AFIL-2026-1002';
    `);

    console.log('4. Resetting CASO-AFIL-2026-1001 to PENDIENTE_AGENCIA with clean real data...');
    const updateRes = await client.query(`
      UPDATE solicitudes_afiliacion_agencia
      SET estado = 'PENDIENTE_AGENCIA',
          cui_dpi = '4000000000005',
          primer_nombre = 'Marvin',
          segundo_nombre = 'Steven',
          primer_apellido = 'Ortiz',
          segundo_apellido = 'Valle',
          telefono = '55555555',
          direccion = 'pinula',
          fecha_nacimiento = '1999-05-31',
          email = 'ortiz20marvin@gmail.com',
          monto_estimado = 250.00,
          id_operador_bloqueo = NULL,
          fecha_bloqueo = NULL,
          id_operador_resuelve = NULL,
          fecha_resolucion = NULL,
          observaciones = 'Registro digital previo. Pendiente depósito y formalización en agencia bancaria.'
      WHERE numero_caso = 'CASO-AFIL-2026-1001'
      RETURNING *;
    `);

    if (updateRes.rows.length === 0) {
      console.log('CASO-AFIL-2026-1001 did not exist, inserting fresh...');
      await client.query(`
        INSERT INTO solicitudes_afiliacion_agencia (
          numero_caso, cui_dpi, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido,
          telefono, direccion, fecha_nacimiento, email, monto_estimado, estado, observaciones
        ) VALUES (
          'CASO-AFIL-2026-1001', '4000000000005', 'Marvin', 'Steven', 'Ortiz', 'Valle',
          '55555555', 'pinula', '1999-05-31', 'ortiz20marvin@gmail.com', 250.00, 'PENDIENTE_AGENCIA',
          'Registro digital previo. Pendiente depósito y formalización en agencia bancaria.'
        );
      `);
    }

    await client.query('COMMIT');
    console.log('Cleanup and migration completed successfully!');

    const casos = await client.query('SELECT id_solicitud, numero_caso, cui_dpi, primer_nombre, primer_apellido, email, estado, id_operador_bloqueo FROM solicitudes_afiliacion_agencia');
    console.log('CURRENT CASES IN DB:', casos.rows);
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Migration failed:', err);
  } finally {
    client.release();
    await pool.end();
  }
}

runCleanupAndMigration();
