/**
 * @file constants.js
 * @description Catálogo centralizado e inmutable de constantes institucionales y reglas de negocio bancario.
 */

module.exports = Object.freeze({
  FINANCIERO: {
    MONTO_MINIMO_APORTACION: 100.00,
    FACTOR_APALANCAMIENTO_MAXIMO: 1.5,
    PORCENTAJE_BENEFICIARIOS_TOTAL: 100.00,
    TASA_INTERES_DEFAULT_CREDITO: 10.00,
    CUENTA_APORTACIONES_ID: 1,
    CUENTA_AHORRO_DISPONIBLE_ID: 2,
    CUENTA_PLAZO_FIJO_ID: 3,
    CUENTA_PLANILLA_ID: 4,
    CUENTA_AHORRO_PROGRAMADO_ID: 5,
  },
  SEGURIDAD: {
    MAX_INTENTOS_LOGIN_FALLIDOS: 3,
    MINUTOS_BLOQUEO_CUENTA: 15,
    MINUTOS_TIMEOUT_PRESENCIA: 2,
    MINUTOS_BLOQUEO_EXPEDIENTE_AGENCIA: 15,
    LONGITUD_CUI_DPI: 13,
    EDAD_MINIMA_LEGAL: 18,
    ADMIN_ROOT_CUI: '1000000000008',
  },
  ROLES: {
    ADMINISTRADOR: 'ADMINISTRADOR',
    OPERADOR: 'OPERADOR',
    EJECUTIVO: 'EJECUTIVO',
    ASOCIADO: 'ASOCIADO',
  },
  ESTADOS_USUARIO: {
    ACTIVO: 'ACTIVO',
    INACTIVO: 'INACTIVO',
    BLOQUEADO: 'BLOQUEADO',
  },
  ESTADOS_ASOCIADO: {
    ACTIVO: 'ACTIVO',
    INACTIVO: 'INACTIVO',
    SUSPENDIDO: 'SUSPENDIDO',
    BLOQUEADO: 'BLOQUEADO',
  },
  ESTADOS_SOLICITUD_AFILIACION: {
    PENDIENTE_AGENCIA: 'PENDIENTE_AGENCIA',
    ATENDIDA: 'ATENDIDA',
    CANCELADA: 'CANCELADA',
    EXPIRADA: 'EXPIRADA',
  },
  ESTADOS_CREDITO: {
    PENDIENTE_FIRMA: 'PENDIENTE_FIRMA',
    EN_REVISION_OPERADOR: 'EN_REVISION_OPERADOR',
    EN_AUTORIZACION_EJECUTIVO: 'EN_AUTORIZACION_EJECUTIVO',
    DEVUELTA_OPERADOR: 'DEVUELTA_OPERADOR',
    APROBADA: 'APROBADA',
    DESEMBOLSADA: 'DESEMBOLSADA',
    RECHAZADA: 'RECHAZADA',
    DENEGADA: 'DENEGADA',
  },
  ESTADOS_CUENTA: {
    ACTIVA: 'ACTIVA',
    BLOQUEADA: 'BLOQUEADA',
    CANCELADA: 'CANCELADA',
  },
});
